services:
  db:
    image: postgres:15-alpine
    container_name: heroes_postgres_container
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: heroes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: heroes_api_container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://dev_user:dev_password@db:5432/heroes_db?schema=public"
      JWT_SECRET: "mindata_secret_2026"
    depends_on:
      - db

volumes:
  postgres_data: