server {
    listen 80;
    
    root /usr/share/nginx/html;
    # Importante: No uses server_name si es local
    
    # Desactivamos redirecciones de Nginx para que no metan la pata
    absolute_redirect off;
    port_in_redirect off;

    location / {
        # Esta es la configuración estándar para SPAs (Single Page Applications)
        # 1. Busca el archivo exacto ($uri)
        # 2. Si no existe, entrega el index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache para archivos estáticos (opcional pero profesional)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}